# permissions for end users to edit gatekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-editor-role
rules:
- apiGroups:
  - charts.gatekeeper.sh
  resources:
  - gatekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.gatekeeper.sh
  resources:
  - gatekeepers/status
  verbs:
  - get
