# permissions for end users to view gatekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-viewer-role
rules:
- apiGroups:
  - charts.gatekeeper.sh
  resources:
  - gatekeepers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.gatekeeper.sh
  resources:
  - gatekeepers/status
  verbs:
  - get
