apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: gatekeeper-helm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: gatekeeper operator
  displayName: Gatekeeper Helm Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gatekeeper
  links:
  - name: Gatekeeper Helm Operator
    url: https://gatekeeper-helm-operator.domain
  maintainers:
  - email: thomasmckay@redhat.com
    name: thomasmckay
  maturity: alpha
  provider:
    name: community
  version: 0.0.0
